// <auto-generated />
namespace CoreITDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Payment_20141121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Payment_20141121));
        
        string IMigrationMetadata.Id
        {
            get { return "201411212210529_Payment_20141121"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
