// <auto-generated />
namespace CoreITDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _20141126_Assignments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20141126_Assignments));
        
        string IMigrationMetadata.Id
        {
            get { return "201411261718081_20141126_Assignments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
