// <auto-generated />
namespace CoreITDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _20141120_Address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20141120_Address));
        
        string IMigrationMetadata.Id
        {
            get { return "201411201851368_20141120_Address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
