// <auto-generated />
namespace CoreITDemo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Billing_11262014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Billing_11262014));
        
        string IMigrationMetadata.Id
        {
            get { return "201411262121590_Billing_11262014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
